Testing

diff --git a/.github/workflows/fullstack-deploy.yml b/.github/workflows/fullstack-deploy.yml
--- a/.github/workflows/fullstack-deploy.yml
+++ b/.github/workflows/fullstack-deploy.yml
@@ -7,68 +7,68 @@ env:
   ENVIRONMENT: dev
     
 jobs:
-  frontend: 
-    name: Deploy frontend
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
+  # frontend: 
+  #   name: Deploy frontend
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Setup Node
-        uses: actions/setup-node@v4 
-        with:
-          node-version: 20 
+  #     - name: Setup Node
+  #       uses: actions/setup-node@v4 
+  #       with:
+  #         node-version: 20 
       
-      - run: |
-          cd frontend
-          npm install 
-          npm run build
+  #     - run: |
+  #         cd frontend
+  #         npm install 
+  #         npm run build
 
-      - uses: aws-actions/configure-aws-credentials@v4
-        with: 
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+  #     - uses: aws-actions/configure-aws-credentials@v4
+  #       with: 
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: us-east-1
 
-      - run: |
-          aws s3 sync frontend/build s3://${{ secrets.FRONTEND_BUCKET }} --delete
-          aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --path "/*"
+  #     - run: |
+  #         aws s3 sync frontend/build s3://${{ secrets.FRONTEND_BUCKET }} --delete
+  #         aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --path "/*"
 
-      # - name: Capture frontend deployment error
-      #   id: deploy
-      #   run: |
-      #     set -o pipefail
-      #     ./deploy.sh 2>&1 | tee deploy.log
+  #     # - name: Capture frontend deployment error
+  #     #   id: deploy
+  #     #   run: |
+  #     #     set -o pipefail
+  #     #     ./deploy.sh 2>&1 | tee deploy.log
         
-      - name: Slack notification for successful deployment 
-        if: success()
-        run: |
-          curl -X POST -H 'Content-type: application/json' \
-          --data "{
-            \"text\": \"✅ *Deployment Successful* 🚀\n\
-            *App:* Frontend\n\
-            *Environment:* $ENVIRONMENT\n\
-            *Branch:* ${{ github.ref_name }}\n\
-            *Triggered by:* ${{ github.actor }}\n\
-            *Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|View Commit>\n\
-            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Logs>\"
-          }" \
-          ${{ secrets.SLACK_WEBHOOK_URL }}
+  #     - name: Slack notification for successful deployment 
+  #       if: success()
+  #       run: |
+  #         curl -X POST -H 'Content-type: application/json' \
+  #         --data "{
+  #           \"text\": \"✅ *Deployment Successful* 🚀\n\
+  #           *App:* Frontend\n\
+  #           *Environment:* $ENVIRONMENT\n\
+  #           *Branch:* ${{ github.ref_name }}\n\
+  #           *Triggered by:* ${{ github.actor }}\n\
+  #           *Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|View Commit>\n\
+  #           <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Logs>\"
+  #         }" \
+  #         ${{ secrets.SLACK_WEBHOOK_URL }}
 
 
-      - name: Slack notification for faliure deployment 
-        if: failure()
-        run: |
-          curl -X POST -H 'Content-type: application/json' \
-          --data "{
-            \"text\": \"❌ *Deployment Failed* 🚨\n\
-            *App:* Frontend\n\
-            *Environment:* $ENVIRONMENT\n\
-            *Branch:* ${{ github.ref_name }}\n\
-            *Triggered by:* ${{ github.actor }}\n\
-            *Job:* ${{ github.job }}\n\
-            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here to view failure logs>\"
-          }" \
-          ${{ secrets.SLACK_WEBHOOK_URL }}
+  #     - name: Slack notification for faliure deployment 
+  #       if: failure()
+  #       run: |
+  #         curl -X POST -H 'Content-type: application/json' \
+  #         --data "{
+  #           \"text\": \"❌ *Deployment Failed* 🚨\n\
+  #           *App:* Frontend\n\
+  #           *Environment:* $ENVIRONMENT\n\
+  #           *Branch:* ${{ github.ref_name }}\n\
+  #           *Triggered by:* ${{ github.actor }}\n\
+  #           *Job:* ${{ github.job }}\n\
+  #           <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here to view failure logs>\"
+  #         }" \
+  #         ${{ secrets.SLACK_WEBHOOK_URL }}
   
   backend: 
     name: Deploy Backend 
